spring:
  config:
    import: aws-parameterstore:/spring-plus/prod/
  cloud:
    aws:
      s3:
        bucket: plus-soomin0209-prod-uploads
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never

jwt:
  secret:
    key: ${JWT_SECRET_KEY}